-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 19:00:31 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Tarea2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tarea2` ;

-- -----------------------------------------------------
-- Schema Tarea2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tarea2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Tarea2` ;

-- -----------------------------------------------------
-- Table `Tarea2`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Usuario` (
  `id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Concesionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Concesionario` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Concesionario` (
  `nombre` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Bus` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Bus` (
  `patente` VARCHAR(6) NOT NULL COMMENT '',
  `Concesionario_nombre` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`patente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Recorrido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Recorrido` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Recorrido` (
  `nombre` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Chofer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Chofer` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Chofer` (
  `rut` VARCHAR(10) NOT NULL COMMENT '',
  `Concesionario_nombre` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`rut`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Paradero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Paradero` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Paradero` (
  `id` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`ViajeB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`ViajeB` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`ViajeB` (
  `bus_patente` VARCHAR(6) NOT NULL COMMENT '',
  `recorrido_nombre` VARCHAR(10) NOT NULL COMMENT '',
  `chofer_rut` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`bus_patente`, `recorrido_nombre`, `chofer_rut`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Tren`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Tren` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Tren` (
  `patente` VARCHAR(6) NOT NULL COMMENT '',
  PRIMARY KEY (`patente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Conductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Conductor` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Conductor` (
  `rut` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`rut`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Linea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Linea` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Linea` (
  `nombre` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Estacion` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Estacion` (
  `nombre` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`ParaderoEnRecorrido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`ParaderoEnRecorrido` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`ParaderoEnRecorrido` (
  `recorrido_nombre` VARCHAR(10) NOT NULL COMMENT '',
  `paradero_id` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`recorrido_nombre`, `paradero_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`EstacionEnLinea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`EstacionEnLinea` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`EstacionEnLinea` (
  `Estacion_nombre` VARCHAR(20) NOT NULL COMMENT '',
  `Linea_nombre` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`Estacion_nombre`, `Linea_nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`ViajeM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`ViajeM` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`ViajeM` (
  `linea_nombre` VARCHAR(20) NOT NULL COMMENT '',
  `conductor_rut` VARCHAR(10) NOT NULL COMMENT '',
  `tren_patente` VARCHAR(6) NOT NULL COMMENT '',
  PRIMARY KEY (`linea_nombre`, `conductor_rut`, `tren_patente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Combinaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Combinaciones` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Combinaciones` (
  `paredero_id` VARCHAR(15) NOT NULL COMMENT '',
  `estacion_nombre` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`paredero_id`, `estacion_nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`Bip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`Bip` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`Bip` (
  `id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`UsuarioEnMetro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`UsuarioEnMetro` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`UsuarioEnMetro` (
  `usuario_id` INT NOT NULL COMMENT '',
  `viajeM_Linea_nombre` VARCHAR(20) NOT NULL COMMENT '',
  `viajeM_Conductor_rut` VARCHAR(10) NOT NULL COMMENT '',
  `viajeM_Tren_patente` VARCHAR(6) NOT NULL COMMENT '',
  `bip_id` INT NOT NULL COMMENT '',
  `estacion_nombre` VARCHAR(20) NOT NULL COMMENT '',
  `hora` DATETIME NULL COMMENT '',
  PRIMARY KEY (`usuario_id`, `viajeM_Linea_nombre`, `viajeM_Conductor_rut`, `viajeM_Tren_patente`, `bip_id`, `estacion_nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`UsuarioEnBus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`UsuarioEnBus` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`UsuarioEnBus` (
  `viajeB_patente` VARCHAR(6) NOT NULL COMMENT '',
  `viajeB_Recorrido_nombre` VARCHAR(10) NOT NULL COMMENT '',
  `viajeB_Chofer_rut` VARCHAR(10) NOT NULL COMMENT '',
  `usuario_id` INT NOT NULL COMMENT '',
  `paradero_id` VARCHAR(15) NOT NULL COMMENT '',
  `bip_id` INT NOT NULL COMMENT '',
  `hora` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`viajeB_patente`, `viajeB_Recorrido_nombre`, `viajeB_Chofer_rut`, `usuario_id`, `paradero_id`, `bip_id`, `hora`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`QuejasMetro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`QuejasMetro` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`QuejasMetro` (
  `usuario_id` INT NOT NULL COMMENT '',
  `viajeM_Usuario_id` INT NOT NULL COMMENT '',
  `viajeM_Linea_name` VARCHAR(20) NOT NULL COMMENT '',
  `viajeM_Conductor_rut` VARCHAR(10) NOT NULL COMMENT '',
  `viajeM_Metro_patente` VARCHAR(6) NOT NULL COMMENT '',
  `viajeM_Bip_id` INT NOT NULL COMMENT '',
  `viajeM_Estacion_name` VARCHAR(20) NOT NULL COMMENT '',
  `mensaje` TEXT(100) NOT NULL COMMENT '',
  `tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario_id`, `viajeM_Usuario_id`, `viajeM_Linea_name`, `viajeM_Conductor_rut`, `viajeM_Metro_patente`, `viajeM_Bip_id`, `viajeM_Estacion_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea2`.`QuejasBus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarea2`.`QuejasBus` ;

CREATE TABLE IF NOT EXISTS `Tarea2`.`QuejasBus` (
  `usuario_id` INT NOT NULL COMMENT '',
  `viajeB_Bus_patente` VARCHAR(6) NOT NULL COMMENT '',
  `viajeB_Recorrido_nombre` VARCHAR(10) NOT NULL COMMENT '',
  `viajeB_Chofer_rut` VARCHAR(10) NOT NULL COMMENT '',
  `viajeB_Usuario_id` INT NOT NULL COMMENT '',
  `viajeB_Paradero_id` VARCHAR(15) NOT NULL COMMENT '',
  `viajeB_Bip_id` INT NOT NULL COMMENT '',
  `mensaje` TEXT(100) NOT NULL COMMENT '',
  `tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario_id`, `viajeB_Bus_patente`, `viajeB_Recorrido_nombre`, `viajeB_Chofer_rut`, `viajeB_Usuario_id`, `viajeB_Paradero_id`, `viajeB_Bip_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
